# Generated by Django 3.1.4 on 2020-12-07 18:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_code', models.CharField(max_length=5, verbose_name='Supervisor Code')),
                ('assistant_name', models.CharField(max_length=150, verbose_name='Supervisor Name')),
                ('seniority', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1, verbose_name='Seniority')),
                ('undesired_days', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Unfavorable Days')),
                ('undesired_slots', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Unfavorable Slots')),
                ('total_assignment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Assignments')),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Authorized')),
            ],
        ),
    ]
