# Generated by Django 2.2.10 on 2020-09-12 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=5, verbose_name='Exam Code')),
                ('course_name', models.CharField(max_length=150, verbose_name='Exam Name')),
                ('course_capacity', models.IntegerField(blank=0, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Exam Capacity')),
                ('sixty_more', models.CharField(choices=[('1', 'More than or equal to 66'), ('0', 'Less than 66')], max_length=20, verbose_name='Is Class Capacity Over 66?')),
                ('slot_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Slot Number')),
                ('lab_or_not', models.CharField(choices=[('1', 'Lab Course'), ('0', 'Standard Course')], max_length=20, verbose_name='Lab or Not')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('desired_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Favorable Days')),
                ('desired_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Favorable Slots')),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Authorized')),
            ],
        ),
        migrations.CreateModel(
            name='SameTimeCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Exam Capacity')),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Authorized')),
                ('course1_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_1_code', to='courses.Courses', verbose_name='First Exam')),
                ('course2_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_2_code', to='courses.Courses', verbose_name='Second Exam')),
            ],
        ),
    ]
